services:
  profiles_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5242:8080"
    container_name: profiles_api
    depends_on:
      postgresql:
        condition: service_started
      mongodb:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${PROFILES_DB_CONN}
      - ConnectionStrings__MongoLogging=${MONGO_LOGGING_CONN}
      - PasswordSettings__Key=${PASSWORD_SECRET_KEY}
  postgresql:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    container_name: profiles_api_data_postgresql
    environment:
      - POSTGRES_DB=ProfilesApiDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - profiles_api_data:/var/lib/postgresql/data
  mongodb:
    image: mongo:latest
    container_name: profiles_api_logs_mongo
    ports:
      - "27017:27017"
    volumes:
      - profiles_api_logs:/data/db
volumes:
  profiles_api_data:
  profiles_api_logs: